---
abstract: 'Catmandu module for Activiti'
author:
  - 'Nicolas Franck <nicolas.franck@ugent.be>'
build_requires:
  Software::License: 0
  Test::Exception: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.42
dynamic_config: 1
generated_by: 'Module::Build version 0.4203, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catmandu-Activiti
provides:
  Catmandu::Activiti:
    file: lib/Catmandu/Activiti.pm
    version: 0.1
  Catmandu::Importer::Activiti::HistoricProcessInstance:
    file: lib/Catmandu/Importer/Activiti/HistoricProcessInstance.pm
  Catmandu::Importer::Activiti::HistoricTask:
    file: lib/Catmandu/Importer/Activiti/HistoricTask.pm
  Catmandu::Importer::Activiti::RuntimeProcessInstance:
    file: lib/Catmandu/Importer/Activiti/RuntimeProcessInstance.pm
  Catmandu::Importer::Activiti::RuntimeTask:
    file: lib/Catmandu/Importer/Activiti/RuntimeTask.pm
  Catmandu::Store::Activiti::HistoricProcessInstance:
    file: lib/Catmandu/Store/Activiti/HistoricProcessInstance.pm
  Catmandu::Store::Activiti::HistoricProcessInstance::Bag:
    file: lib/Catmandu/Store/Activiti/HistoricProcessInstance.pm
requires:
  Activiti::Rest::Client: 0.1
  Carp: 0
  Catmandu: 0.8014
  perl: v5.10.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.1
